# Site settings
title: St John Institutional Repository
email: communications@sjbdcs.edu
description: St John Baptist De La Salle Catholic School, Addis Ababa - Institutional Repository for Research and E-content Archives
baseurl: ""
url: ""


# Google analytics ID: Remove or use your own!
google_analytics: 
google_analytics_4: 
google_tag_manager: 

# Footer info
affiliation: >
    St John Baptist De La Salle Catholic School<br/>
    Research and E-content Archives<br/>
    <a href="https://sjbdcs.org" target="_blank">Home</a><br/>
    

location: >
  <a href="https://www.google.com/maps/place/St.+John+Baptist+De+La+Salle+Catholic+School/@9.061537,38.688478,15z/data=!4m2!3m1!1s0x0:0xd14ea09881b01f6c?sa=X&ved=2ahUKEwiNtK_I-5v4AhXE7rsIHY0oA2UQ_BJ6BAhoEAU" target="_blank">Library</a><br/>
  Asco, Addis Sefer <br/>
  171120 - Addis Ababa, Ethiopia<br/>


contact: >
    <a href="mailto:communications@sjbdcs.org" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact SJBDCS-IR via email</a> <br/>
    
# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: research
  - name: software
# - name: team
# - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Bryngelson
  first_name: [Spencer H.]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
